export type Sector = {
  slug: string;
  name: string;
  headline: string;
  subheadline: string;
  metaTitle: string;
  metaDesc: string;
  stat1: { value: string; label: string };
  stat2: { value: string; label: string };
  stat3: { value: string; label: string };
  painPoints: { title: string; desc: string }[];
  useCases: { emoji: string; title: string; desc: string; result: string }[];
  faq: { q: string; a: string }[];
  relatedPosts: { slug: string; title: string }[];
};

export const sectors: Record<string, Sector> = {
  avocats: {
    slug: "avocats",
    name: "Avocats & Cabinets juridiques",
    headline: "L'agent IA qui gère l'administratif pendant que vous plaidez.",
    subheadline: "Claws installe OpenClaw sur votre machine et le configure pour votre cabinet. Triage des emails, suivi des dossiers, relances, comptes-rendus. Vos données ne quittent jamais votre cabinet.",
    metaTitle: "OpenClaw pour avocats et cabinets juridiques | Installation Claws",
    metaDesc: "Claws installe et configure OpenClaw pour votre cabinet juridique. Triage emails, suivi dossiers, relances automatiques. Installation locale, RGPD natif. À partir de 189€.",
    stat1: { value: "8h", label: "gagnées par semaine en moyenne" },
    stat2: { value: "0", label: "donnée client sur un cloud tiers" },
    stat3: { value: "2h", label: "délai d'installation" },
    painPoints: [
      { title: "Boite mail ingérable", desc: "Entre les clients, les opposants, les greffes et les huissiers, votre boite reçoit 80+ emails par jour. Trier ça prend 1h le matin. Chaque matin." },
      { title: "Relances chronophages", desc: "Les devis non signés, les honoraires impayés, les clients silencieux. Relancer manuellement est épuisant et ça passe souvent à la trappe." },
      { title: "RGPD et confidentialité", desc: "Vos dossiers sont couverts par le secret professionnel. Vous ne pouvez pas confier vos emails clients à ChatGPT ou Notion AI. C'est un risque déontologique réel." },
      { title: "Comptes-rendus de RDV", desc: "Après chaque consultation, il faut résumer, noter les prochaines étapes, mettre à jour le dossier. 15 min de travail répétitif après chaque rendez-vous." },
    ],
    useCases: [
      { emoji: "01",
        title: "Triage intelligent des emails",
        desc: "L'agent classe chaque email entrant par priorité et par dossier. Les demandes urgentes remontent immédiatement. Les newsletters disparaissent. Vous commencez la journée avec un résumé de 10 lignes.",
        result: "1h de lecture d'emails → 10 minutes.",
      },
      { emoji: "02",
        title: "Relances honoraires automatiques",
        desc: "L'agent surveille vos factures impayées et envoie des relances graduelles, douce à J+15, ferme à J+30, dans le ton que vous avez choisi. Il s'arrête dès réception du paiement.",
        result: "Taux de recouvrement à 30 jours amélioré de 40%.",
      },
      { emoji: "03",
        title: "Comptes-rendus de consultation",
        desc: "Après chaque RDV, dictez 2 minutes à voix haute sur votre téléphone. L'agent transforme ça en compte-rendu structuré, mis en forme, prêt à être versé au dossier.",
        result: "15 min de saisie → 2 min de dictée.",
      },
      { emoji: "04",
        title: "Suivi des délais procéduraux",
        desc: "L'agent surveille vos calendriers de procédure et vous alerte 7, 3 et 1 jour avant chaque échéance. Plus aucune date qui passe entre les mailles.",
        result: "Zéro oubli de délai procédural.",
      },
      { emoji: "05",
        title: "Veille jurisprudentielle",
        desc: "L'agent surveille chaque semaine les nouvelles décisions dans vos domaines de pratique (droit des affaires, droit du travail, etc.) et vous envoie un résumé le lundi matin.",
        result: "Veille jurisprudentielle sans abonnement à prix d'or.",
      },
    ],
    faq: [
      { q: "Le secret professionnel est-il respecté ?", a: "Oui. L'agent tourne sur votre machine, dans votre cabinet. Aucune donnée client ne transite par un serveur externe. Le seul appel réseau est vers le modèle de langage (Anthropic Claude), qui ne conserve pas les données selon sa politique de confidentialité. Pour les dossiers ultra-sensibles, un modèle local peut être utilisé." },
      { q: "L'agent peut-il accéder à mes logiciels métier (Secib, Jarvis) ?", a: "Partiellement. OpenClaw peut lire des exports de ces logiciels et interagir via leurs APIs quand elles existent. Claws étudie les possibilités d'intégration au cas par cas lors de l'installation." },
      { q: "Combien de temps pour que l'agent soit opérationnel ?", a: "2 heures après la commande. Claws installe et configure tout à distance, sans que vous ayez à intervenir techniquement." },
      { q: "Un agent peut-il rédiger des conclusions ou des actes ?", a: "Il peut générer des premiers jets à partir de vos notes ou de templates que vous avez validés. La relecture et la signature restent de votre responsabilité. C'est un outil d'aide à la rédaction, pas un substitut à votre expertise juridique." },
    ],
    relatedPosts: [
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails professionnels" },
      { slug: "openclaw-rgpd-donnees-locales", title: "OpenClaw et RGPD : vos données restent chez vous" },
    ],
  },

  medecins: {
    slug: "medecins",
    name: "Médecins & Professionnels de santé",
    headline: "Moins d'administratif. Plus de temps pour vos patients.",
    subheadline: "Claws installe OpenClaw sur votre machine et le configure pour votre activité médicale. Gestion RDV, comptes-rendus, relances patients. Zéro donnée de santé sur un cloud.",
    metaTitle: "OpenClaw pour médecins et professionnels de santé | Installation Claws",
    metaDesc: "Claws installe OpenClaw pour les médecins et professionnels de santé. Gestion RDV, comptes-rendus, relances patients. Données de santé 100% locales. À partir de 189€.",
    stat1: { value: "30%", label: "du temps médical = tâches administratives" },
    stat2: { value: "0", label: "donnée patient sur un serveur externe" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "Surcharge administrative", desc: "Ordonnances, comptes-rendus, certificats, courriers aux spécialistes. L'administratif représente jusqu'à 30% du temps d'un médecin généraliste. Du temps pris sur les patients." },
      { title: "Données de santé sensibles", desc: "Les données de santé sont parmi les plus protégées par le RGPD. Utiliser des outils cloud américains pour traiter des informations patients est un risque juridique et éthique majeur." },
      { title: "Gestion du secrétariat", desc: "Sans secrétaire ou avec un secrétariat débordé, les demandes de RDV s'accumulent, les relances sont oubliées, les messages ne sont pas triés par urgence." },
      { title: "Veille médicale chronophage", desc: "Les recommandations HAS, les nouvelles études, les mises à jour de protocoles, rester à jour prend du temps que vous n'avez pas." },
    ],
    useCases: [
      { emoji: "06",
        title: "Comptes-rendus de consultation",
        desc: "Dictez vos observations après chaque consultation. L'agent structure en compte-rendu médical formaté, avec les antécédents, les prescriptions et les prochaines étapes.",
        result: "20 min de saisie → 3 min de dictée.",
      },
      { emoji: "07",
        title: "Gestion des demandes de RDV",
        desc: "L'agent lit les demandes de RDV par email ou message, les classe par urgence et propose des créneaux disponibles. Les confirmations et rappels sont envoyés automatiquement.",
        result: "Réduction des no-shows de 35%.",
      },
      { emoji: "08",
        title: "Relances patients et suivis",
        desc: "Pour les patients chroniques, l'agent envoie des rappels de contrôle, de renouvellement d'ordonnance ou de vaccination selon les protocoles que vous définissez.",
        result: "Meilleure observance, moins d'oublis de suivi.",
      },
      { emoji: "09",
        title: "Triage et réponses aux courriers",
        desc: "L'agent trie les emails et messages entrants, identifie les urgences, prépare des réponses types pour les demandes fréquentes et vous soumet les cas qui nécessitent votre attention.",
        result: "1h de courriers → 15 minutes de validation.",
      },
      { emoji: "10",
        title: "Veille médicale hebdomadaire",
        desc: "Chaque lundi, l'agent vous envoie un résumé des nouvelles recommandations HAS, des études dans vos domaines et des alertes de pharmacovigilance pertinentes.",
        result: "Restez à jour sans y passer vos soirées.",
      },
    ],
    faq: [
      { q: "Les données patients sont-elles sécurisées ?", a: "Oui. L'agent tourne sur votre propre machine, dans votre cabinet. Aucune donnée de santé ne transite par un cloud externe. C'est architecturalement conforme aux exigences RGPD pour les données de santé." },
      { q: "OpenClaw est-il compatible avec les logiciels médicaux (Doctolib, Maiia, Medistory) ?", a: "OpenClaw peut s'interfacer avec les APIs de ces outils quand elles existent. Claws étudie les possibilités d'intégration lors de l'installation selon votre stack." },
      { q: "Un agent peut-il faire des prescriptions ou des diagnostics ?", a: "Non, et ce n'est pas son rôle. L'agent est un outil administratif et d'aide à la documentation. Le diagnostic et la prescription restent exclusivement de votre responsabilité médicale." },
      { q: "L'installation nécessite-t-elle une interruption d'activité ?", a: "Non. L'installation se fait à distance, sans interruption de votre activité. Claws configure tout en arrière-plan en moins de 2 heures." },
    ],
    relatedPosts: [
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails" },
      { slug: "openclaw-rgpd-donnees-locales", title: "OpenClaw et RGPD : vos données restent chez vous" },
    ],
  },

  btp: {
    slug: "btp",
    name: "BTP & Artisans",
    headline: "L'agent IA qui gère vos devis, relances et chantiers.",
    subheadline: "Votre agent OpenClaw automatise les devis, les relances et le suivi des chantiers. Vous posez les carreaux, OpenClaw gère l'administratif.",
    metaTitle: "OpenClaw pour BTP et artisans | Automatisation devis et chantiers | Claws",
    metaDesc: "Claws installe OpenClaw pour les artisans et entreprises BTP. Devis automatisés, relances clients, suivi chantiers. Installation locale. À partir de 189€.",
    stat1: { value: "5h", label: "perdues par semaine en administratif" },
    stat2: { value: "60%", label: "des devis jamais relancés" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "Les devis prennent trop de temps", desc: "Répondre à chaque demande de devis prend 30 à 45 minutes. Multiplié par 10 demandes par semaine dont la moitié ne donnent rien, c'est un gouffre de temps." },
      { title: "Les relances partent à la trappe", desc: "Un devis envoyé sans réponse. On se dit qu'on va rappeler. On oublie. Le chantier part chez un concurrent. Ça arrive à tout le monde, tout le temps." },
      { title: "Suivi des chantiers en cours", desc: "Plusieurs chantiers en parallèle, des sous-traitants, des livraisons à coordonner. Garder tout en tête est épuisant et les erreurs coûtent cher." },
      { title: "Les appels d'offres passés", desc: "Les appels d'offres publics et privés passent souvent inaperçus. Faire une veille manuelle prend du temps et reste incomplet." },
    ],
    useCases: [
      { emoji: "11",
        title: "Devis automatisés",
        desc: "L'agent reçoit une demande de devis par email ou formulaire, extrait les informations clés (surface, type de travaux, localisation) et génère un devis pré-rempli à partir de vos templates. Vous validez en 5 minutes.",
        result: "45 min de devis → 5 min de validation.",
      },
      { emoji: "12",
        title: "Relances clients systématiques",
        desc: "Chaque devis envoyé est suivi automatiquement. J+3 : relance douce. J+7 : relance avec disponibilité. J+14 : dernière tentative. L'agent s'arrête dès que le client répond.",
        result: "Taux de signature amélioré de 25%.",
      },
      { emoji: "13",
        title: "Suivi des chantiers",
        desc: "L'agent tient un tableau de bord de vos chantiers en cours : avancement, prochaines étapes, matériaux à commander, sous-traitants à contacter. Un briefing chaque matin sur votre téléphone.",
        result: "Fini les oublis qui font perdre des journées.",
      },
      { emoji: "14",
        title: "Veille appels d'offres",
        desc: "L'agent surveille les plateformes d'appels d'offres (BOAMP, marchés locaux) dans votre secteur géographique et votre domaine, et vous alerte dès qu'une opportunité correspond à votre profil.",
        result: "Ne ratez plus aucun marché dans votre zone.",
      },
      { emoji: "15",
        title: "Communication chantier",
        desc: "L'agent peut envoyer des mises à jour automatiques aux clients sur l'avancement de leur chantier : début des travaux, étapes clés, fin prévue. Moins d'appels entrants, plus de satisfaction client.",
        result: "Réduction de 50% des appels 'où en êtes-vous'.",
      },
    ],
    faq: [
      { q: "Je ne suis pas à l'aise avec la technologie, est-ce pour moi ?", a: "Oui. Claws installe et configure tout. Une fois en place, vous interagissez avec l'agent via WhatsApp ou Telegram, comme vous envoyez un message. Pas de logiciel à apprendre, pas d'interface compliquée." },
      { q: "L'agent peut-il s'intégrer à mon logiciel de devis (Batappli, Quotit, Obat) ?", a: "Partiellement selon les outils. Claws étudie les possibilités d'intégration lors de l'installation. Dans tous les cas, l'agent peut travailler avec des templates Word ou Excel que vous utilisez déjà." },
      { q: "Est-ce que ça marche pour un artisan solo ?", a: "C'est même là où le ROI est le plus fort. Un artisan seul porte tout l'administratif sans aide. Un agent IA qui gère les devis et les relances libère plusieurs heures par semaine immédiatement." },
      { q: "L'agent peut-il gérer les appels téléphoniques ?", a: "Pas directement. Il gère les emails, messages et formulaires. Pour les appels téléphoniques, des solutions complémentaires existent que Claws peut vous recommander." },
    ],
    relatedPosts: [
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails" },
      { slug: "openclaw-pour-artisans-tpe", title: "OpenClaw pour les artisans : guide pratique" },
    ],
  },

  agences: {
    slug: "agences",
    name: "Agences & Consultants",
    headline: "L'agent IA qui travaille la nuit pendant que vous dormez.",
    subheadline: "Claws configure OpenClaw pour votre agence : veille, reporting, prospection, comptes-rendus. Opérationnel en 2h. Vos clients n'ont pas besoin de savoir.",
    metaTitle: "OpenClaw pour agences et consultants | Automatisation | Claws",
    metaDesc: "Claws installe OpenClaw pour les agences et consultants. Veille, reporting, prospection, comptes-rendus automatiques. Installation locale. À partir de 189€.",
    stat1: { value: "12h", label: "de reporting par mois par client" },
    stat2: { value: "3x", label: "plus de clients suivis avec le même temps" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "Le reporting prend trop de temps", desc: "Compiler les stats, rédiger les analyses, formatter les slides. Chaque client = plusieurs heures par mois. Pur temps non facturable, non différenciant." },
      { title: "La veille est impossible à tenir", desc: "Surveiller les concurrents de vos clients, les tendances du marché, les mentions de leur marque, c'est un travail à plein temps que vous n'avez pas." },
      { title: "La prospection tombe toujours", desc: "Quand les missions s'accumulent, la prospection s'arrête. Quand les missions se terminent, il faut repartir de zéro. Ce cycle boom-bust est épuisant." },
      { title: "Comptes-rendus interminables", desc: "Après chaque réunion client, il faut rédiger le compte-rendu, l'envoyer, s'assurer que tout le monde est aligné. 30 minutes qui s'allongent toujours." },
    ],
    useCases: [
      { emoji: "16",
        title: "Reporting clients automatisé",
        desc: "L'agent collecte les données de vos outils (Analytics, Meta Ads, LinkedIn, etc.) et génère un rapport mensuel formaté selon vos templates. Vous relisez et envoyez.",
        result: "12h de reporting → 1h de relecture.",
      },
      { emoji: "17",
        title: "Veille concurrentielle en temps réel",
        desc: "L'agent surveille les sites des concurrents de vos clients, leurs réseaux sociaux, leurs annonces de recrutement, leurs avis. Chaque semaine, un résumé des mouvements importants.",
        result: "Conseil proactif sans effort de veille.",
      },
      { emoji: "18",
        title: "Prospection en continu",
        desc: "L'agent surveille les signaux d'affaires (nouvelles levées de fonds, recrutements marketing, changements de direction) et identifie les prospects chauds à contacter. Il prépare l'email de prise de contact personnalisé.",
        result: "Pipeline alimenté même en période de forte activité.",
      },
      { emoji: "19",
        title: "Comptes-rendus de réunion",
        desc: "Envoyez l'enregistrement ou vos notes de la réunion. L'agent produit un compte-rendu structuré avec les décisions prises, les actions et les responsables.",
        result: "CR envoyé dans l'heure qui suit la réunion.",
      },
      { emoji: "20",
        title: "Premiers jets de livrables",
        desc: "Brief stratégique, analyse de marché, recommandations, l'agent produit un premier jet à partir de votre brief et des données disponibles. Vous affinez, vous signez.",
        result: "Démarrez chaque livrable à 60%, pas à 0%.",
      },
    ],
    faq: [
      { q: "Mes clients peuvent-ils savoir que j'utilise un agent IA ?", a: "Non, si vous ne le dites pas. L'agent produit des livrables que vous relisez et envoyez depuis votre propre adresse. Il est transparent pour vos clients." },
      { q: "L'agent peut-il poster sur les réseaux sociaux de mes clients ?", a: "Oui, avec vos autorisations. L'agent peut programmer et publier des contenus sur LinkedIn, Instagram, etc. selon un calendrier éditorial que vous validez." },
      { q: "Est-ce que ça fonctionne pour un consultant solo ?", a: "C'est le profil idéal. Un consultant solo qui automatise le reporting et la veille peut doubler son nombre de clients sans recruter. Le ROI est immédiat." },
      { q: "L'agent peut-il travailler avec Google Docs, Notion ou Airtable ?", a: "Oui. OpenClaw s'intègre avec ces outils. L'agent peut lire, écrire et mettre à jour vos documents de travail directement." },
    ],
    relatedPosts: [
      { slug: "agent-ia-veille-strategique-entreprise", title: "Agent IA pour la veille stratégique" },
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails" },
    ],
  },

  entrepreneurs: {
    slug: "entrepreneurs",
    name: "Entrepreneurs & Startups",
    headline: "L'agent IA qui s'occupe de l'opérationnel pendant que vous construisez.",
    subheadline: "Claws installe OpenClaw et le configure pour votre activité. Emails, prospection, reporting, veille, votre agent OpenClaw gère l'opérationnel. Vous construisez.",
    metaTitle: "OpenClaw pour entrepreneurs et startups | Installation Claws",
    metaDesc: "Claws installe OpenClaw pour les entrepreneurs et startups. Emails, prospection, reporting investisseurs, veille marché. Installation locale. À partir de 189€.",
    stat1: { value: "3h", label: "gagnées par jour sur l'opérationnel" },
    stat2: { value: "0", label: "donnée stratégique sur un cloud tiers" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "Vous faites tout vous-même", desc: "Répondre aux emails, relancer les prospects, préparer les reportings investisseurs, suivre les partenaires, chaque tâche vous vole du temps de construction produit ou business." },
      { title: "La prospection tombe quand ça charge", desc: "Dès que les opérations s'emballent, la prospection s'arrête. Résultat : un pipeline qui se vide sans que vous vous en rendiez compte, jusqu'au creux suivant." },
      { title: "La veille est impossible à tenir", desc: "Suivre les concurrents, les levées de fonds du secteur, les signaux faibles du marché, c'est stratégique mais personne n'a le temps de le faire correctement." },
      { title: "Le reporting investisseurs est chronophage", desc: "Compiler les métriques, rédiger l'update mensuel, préparer le deck. Des heures de travail à faible valeur ajoutée que vous ne pouvez pas déléguer facilement." },
    ],
    useCases: [
      { emoji: "01",
        title: "Gestion des emails et inbox zéro",
        desc: "L'agent trie votre boite mail, classe par priorité (investisseurs, clients, partenaires, opérationnel), prépare les réponses aux messages fréquents et vous présente chaque matin un résumé des 5 choses importantes.",
        result: "2h de gestion mail → 20 min de validation.",
      },
      { emoji: "02",
        title: "Prospection et suivi pipeline",
        desc: "L'agent surveille les signaux d'achat (recrutements, levées, changements de poste) et identifie les bons moments pour contacter vos prospects. Il prépare des emails personnalisés et relance automatiquement les leads silencieux.",
        result: "Pipeline alimenté en continu, même en période de rush.",
      },
      { emoji: "03",
        title: "Reporting investisseurs automatisé",
        desc: "L'agent collecte vos métriques clés (MRR, churn, CAC, pipeline), les consolide et génère un premier draft de votre update mensuel selon votre template. Vous relisez, vous ajustez, vous envoyez.",
        result: "Update investisseurs en 30 min au lieu de 3h.",
      },
      { emoji: "04",
        title: "Veille concurrentielle et marché",
        desc: "L'agent surveille vos concurrents (site, LinkedIn, offres d'emploi, avis) et les signaux du marché (nouvelles réglementations, tendances, partenariats sectoriels). Chaque semaine, un briefing de 10 lignes.",
        result: "Toujours en avance sur votre marché, sans y passer votre temps.",
      },
      { emoji: "05",
        title: "Coordination équipe et partenaires",
        desc: "L'agent envoie les points hebdos, collecte les statuts des projets en cours, relance les actions non closes et tient à jour votre todo list stratégique. Moins de réunions de coordination, plus d'exécution.",
        result: "Moins de réunions. Plus de livré.",
      },
    ],
    faq: [
      { q: "Un agent IA peut-il remplacer mon premier recrutement ?", a: "Pour les tâches répétitives à faible valeur (gestion email, reporting, veille, relances), oui. Un agent peut absorber l'équivalent de 10 à 15h/semaine de travail administratif, ce qui repousse le moment où vous avez besoin d'un premier ops ou assistant." },
      { q: "L'agent peut-il accéder à mes outils (Notion, Slack, Linear) ?", a: "Oui. OpenClaw s'intègre avec les principaux outils SaaS via API. Claws configure les connexions lors de l'installation selon votre stack." },
      { q: "Est-ce que mes données stratégiques sont en sécurité ?", a: "Oui. L'agent tourne sur votre propre machine. Vos plans, vos données clients, votre pipeline, rien ne part sur un serveur externe. C'est l'avantage structurel du local vs les outils cloud." },
      { q: "Est-ce adapté à une entreprise de 1 personne ?", a: "C'est même le cas d'usage le plus rentable. Un fondateur seul qui délègue l'opérationnel à un agent peut se consacrer à 100% à ce qui crée de la valeur. Le ROI est immédiat." },
    ],
    relatedPosts: [
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails professionnels" },
      { slug: "agent-ia-veille-strategique-entreprise", title: "Agent IA pour la veille stratégique" },
    ],
  },

  freelances: {
    slug: "freelances",
    name: "Freelances & Indépendants",
    headline: "Facturer plus. Prospecter moins. Dormir mieux.",
    subheadline: "Votre agent OpenClaw prospecte, relance et facture pendant que vous êtes en mission. Installation locale. Vos données clients ne quittent pas votre machine.",
    metaTitle: "OpenClaw pour freelances et indépendants | Installation Claws",
    metaDesc: "Claws installe OpenClaw pour les freelances et indépendants. Prospection continue, relances, facturation, onboarding clients. Installation locale. À partir de 189€.",
    stat1: { value: "30%", label: "du temps freelance = admin non facturable" },
    stat2: { value: "2x", label: "plus de clients avec le même temps disponible" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "La prospection s'arrête quand vous êtes en mission", desc: "Vous êtes soit en train de travailler pour un client, soit en train d'en chercher un autre. Rarement les deux en même temps. Résultat : des creux d'activité évitables." },
      { title: "Les relances vous mettent mal à l'aise", desc: "Relancer un devis non signé ou une facture impayée est inconfortable. Donc vous attendez. Et parfois l'argent ne rentre pas, ou arrive trop tard." },
      { title: "L'onboarding client recommence à zéro", desc: "Chaque nouveau client : le même questionnaire, les mêmes accès à demander, les mêmes documents à envoyer. 2 à 3 heures de travail non facturable à chaque fois." },
      { title: "L'admin grignote vos soirées", desc: "Facturation, suivi des temps, réponses aux emails, mise à jour des propositions commerciales, des heures chaque semaine qui pourraient être facturées ou récupérées." },
    ],
    useCases: [
      { emoji: "06",
        title: "Prospection en continu",
        desc: "L'agent surveille les signaux d'achat (nouveaux postes ouverts, changements de direction, annonces de croissance) dans votre cible et vous alerte quand le timing est bon pour contacter. Il prépare l'email d'approche personnalisé.",
        result: "Pipeline alimenté même en pleine mission client.",
      },
      { emoji: "07",
        title: "Relances devis et factures automatiques",
        desc: "Chaque devis envoyé est suivi. J+3 : rappel doux. J+7 : relance directe. J+14 : dernière tentative. Pour les factures : même système. L'agent s'arrête dès réception. Vous n'avez plus à y penser.",
        result: "Délai moyen de paiement réduit de 12 jours.",
      },
      { emoji: "08",
        title: "Onboarding client automatisé",
        desc: "Dès qu'un devis est signé, l'agent déclenche l'onboarding : questionnaire de lancement, demande d'accès, envoi du contrat, création des dossiers. En 10 minutes ce qui prenait 3 heures.",
        result: "Onboarding client en 10 min. Première impression parfaite.",
      },
      { emoji: "09",
        title: "Gestion des emails clients",
        desc: "L'agent trie vos emails, identifie les urgences, prépare des réponses pour les demandes fréquentes et vous soumet un résumé quotidien. Vous répondez aux emails importants, pas à tous les emails.",
        result: "Inbox sous contrôle. Zéro message urgent qui passe.",
      },
      { emoji: "10",
        title: "Suivi des temps et facturation",
        desc: "L'agent collecte vos logs de temps (Toggl, Harvest ou notes simples), les consolide par client et génère vos factures mensuelles pré-remplies. Vous vérifiez et envoyez.",
        result: "Facturation mensuelle en 15 min au lieu de 2h.",
      },
    ],
    faq: [
      { q: "Je suis solo, est-ce que ça vaut l'installation ?", a: "Oui, et c'est même là où le ROI est le plus visible. Si l'agent vous économise 8h d'admin par mois et que vous facturez 100€/h, il se rembourse en moins de 2 mois." },
      { q: "Mes données clients sont-elles protégées ?", a: "L'agent tourne sur votre propre machine. Vos contrats, emails clients, données de facturation ne passent pas par un cloud tiers. C'est architecturalement plus sûr que Notion ou Google Drive." },
      { q: "L'agent peut-il gérer mon CRM (Pipedrive, HubSpot, Notion CRM) ?", a: "Oui pour les outils qui ont une API. Claws configure les connexions lors de l'installation. L'agent peut créer des deals, mettre à jour des contacts et envoyer des emails directement depuis votre CRM." },
      { q: "Est-ce que l'agent peut répondre à mes clients à ma place ?", a: "Il peut préparer des réponses que vous validez, ou répondre automatiquement aux questions fréquentes prédéfinies. La configuration est la vôtre : vous choisissez ce qui part automatiquement et ce qui passe par vous." },
    ],
    relatedPosts: [
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails" },
      { slug: "automatiser-relances-commerciales-agent-ia", title: "Automatiser les relances commerciales" },
    ],
  },

  createurs: {
    slug: "createurs",
    name: "Créateurs de contenu",
    headline: "Créez. L'agent s'occupe du reste.",
    subheadline: "Votre agent OpenClaw gère la veille, le repurposing et les réponses communauté. Moins de logistique. Plus de création. Données chez vous, pas sur le cloud.",
    metaTitle: "OpenClaw pour créateurs de contenu | YouTube, LinkedIn, Podcast | Claws",
    metaDesc: "Claws installe OpenClaw pour les créateurs de contenu. Veille tendances, repurposing automatique, planning éditorial. Installation locale. À partir de 189€.",
    stat1: { value: "60%", label: "du temps créateur = tâches non créatives" },
    stat2: { value: "3x", label: "plus de contenus publiés avec le même effort" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "La veille prend autant de temps que la création", desc: "Suivre les tendances, surveiller les concurrents, identifier les sujets qui buzzent, sans système, c'est du scroll infini sans résultat clair." },
      { title: "Le repurposing ne se fait jamais", desc: "Vous savez qu'une vidéo YouTube pourrait devenir 5 posts LinkedIn, 3 threads Twitter et 1 newsletter. Mais transformer le contenu prend du temps. Donc ça ne se fait jamais." },
      { title: "La communauté est impossible à suivre", desc: "Commentaires YouTube, DMs Instagram, réponses LinkedIn, quand ça décolle, répondre à tout devient un job à plein temps. Mais ne pas répondre tue l'engagement." },
      { title: "Le planning éditorial se vide", desc: "Le lundi vous avez 10 idées. Le mercredi vous en cherchez une. Sans système de capture et de planification, l'inspiration est gaspillée et les calendriers restent vides." },
    ],
    useCases: [
      { emoji: "11",
        title: "Veille tendances automatisée",
        desc: "L'agent surveille chaque jour les sujets qui montent dans votre niche (Reddit, YouTube trending, Google Trends, Twitter/X). Chaque matin, un brief de 5 idées de contenu avec les angles qui fonctionnent.",
        result: "Plus jamais à court d'idées pertinentes.",
      },
      { emoji: "12",
        title: "Repurposing automatique",
        desc: "Envoyez votre vidéo, podcast ou article. L'agent génère : la transcription, un résumé, 5 posts LinkedIn avec angles différents, 3 stories, un thread Twitter et un extrait newsletter. Vous choisissez, vous publiez.",
        result: "1 contenu → 10 formats. Sans effort supplémentaire.",
      },
      { emoji: "13",
        title: "Réponses communauté",
        desc: "L'agent surveille vos commentaires YouTube et DMs, identifie les questions récurrentes et prépare des réponses dans votre style. Les cas complexes ou sensibles vous sont soumis. Vous approuvez, l'agent envoie.",
        result: "Taux de réponse de 100%, engagement préservé.",
      },
      { emoji: "14",
        title: "Planning éditorial intelligent",
        desc: "L'agent tient votre calendrier de contenu à jour. Il vous rappelle les deadlines, comble les trous avec des suggestions et s'assure que vos publications sont régulières même quand l'inspiration est là mais le temps pas.",
        result: "Consistance éditoriale même les semaines chargées.",
      },
      { emoji: "15",
        title: "Recherche et brief de contenu",
        desc: "Donnez un sujet à l'agent. Il cherche les meilleures sources, compile les angles pertinents, identifie les questions que pose l'audience sur ce sujet et vous livre un brief complet en 10 minutes.",
        result: "Brief contenu en 10 min. Tournage/rédaction au niveau supérieur.",
      },
    ],
    faq: [
      { q: "L'agent peut-il publier sur mes réseaux à ma place ?", a: "Oui avec vos autorisations. Il peut programmer et publier sur LinkedIn, Instagram, Twitter/X selon votre calendrier éditorial. Vous pouvez choisir de tout valider avant publication ou d'automatiser certains formats." },
      { q: "L'agent peut-il écrire dans mon style ?", a: "Oui, avec une phase d'apprentissage. Plus vous lui fournissez de vos contenus existants, mieux il en capture le ton, le vocabulaire et la structure. La plupart des créateurs voient une vraie ressemblance après 2 semaines." },
      { q: "Quelles plateformes sont supportées ?", a: "YouTube (transcription, commentaires), LinkedIn, Instagram, Twitter/X, TikTok (partiel), podcasts, newsletters. Claws configure les connexions selon vos plateformes lors de l'installation." },
      { q: "L'agent peut-il analyser mes performances ?", a: "Oui. Il peut collecter vos analytics (vues, reach, engagement, croissance) et vous envoyer un rapport hebdomadaire avec les contenus qui ont le mieux performé et des recommandations pour la suite." },
    ],
    relatedPosts: [
      { slug: "agent-ia-veille-strategique-entreprise", title: "Agent IA pour la veille stratégique" },
      { slug: "agent-ia-gestion-emails-professionnels", title: "Agent IA pour gérer vos emails" },
    ],
  },

  cfo: {
    slug: "cfo",
    name: "DAF & Directeurs financiers",
    headline: "Moins de tableurs. Plus de décisions.",
    subheadline: "Claws installe OpenClaw et le configure pour votre direction financière. Reporting automatisé, alertes trésorerie, clôtures accélérées. Données financières 100% locales.",
    metaTitle: "OpenClaw pour DAF et directeurs financiers | Installation Claws",
    metaDesc: "Claws installe OpenClaw pour les DAF et directeurs financiers. Reporting automatisé, alertes trésorerie, clôtures accélérées. Données 100% locales. À partir de 189€.",
    stat1: { value: "40%", label: "du temps DAF = consolidation et reporting" },
    stat2: { value: "0", label: "donnée financière sur un cloud non maîtrisé" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "La consolidation mange les lundis", desc: "Récupérer les chiffres de chaque département, nettoyer les données, consolider dans Excel, corriger les erreurs de formule. C'est des heures de travail répétitif à faible valeur analytique." },
      { title: "Les alertes trésorerie arrivent trop tard", desc: "Vous découvrez un problème de trésorerie quand il est déjà là. Sans monitoring en temps réel, les signaux faibles passent inaperçus jusqu'à ce qu'ils deviennent urgents." },
      { title: "Les données financières sont hypersensibles", desc: "Confier vos données financières à des outils cloud américains (Notion, Airtable, Google Sheets partagés) est un risque de confidentialité majeur. Et souvent contraire à vos politiques internes." },
      { title: "Le suivi budgétaire est manuel", desc: "Comparer budget vs réel par département, calculer les écarts, identifier les dérives, sans automatisation, c'est un travail hebdomadaire qui prend une demi-journée." },
    ],
    useCases: [
      { emoji: "16",
        title: "Reporting financier automatisé",
        desc: "L'agent collecte les données de vos outils comptables (Sage, QuickBooks, Pennylane, exports CSV) et génère automatiquement vos tableaux de bord P&L, trésorerie et bilan selon vos templates. Disponible chaque matin sans intervention.",
        result: "Reporting mensuel en 30 min au lieu d'une journée.",
      },
      { emoji: "17",
        title: "Alertes trésorerie proactives",
        desc: "L'agent surveille votre trésorerie en temps réel et vous alerte dès qu'un seuil critique approche (solde bas, décalage encaissement/décaissement, facture importante non réglée). Vous agissez avant que ça devienne urgent.",
        result: "Zéro surprise trésorerie. Toujours en avance.",
      },
      { emoji: "18",
        title: "Suivi budgétaire budget vs réel",
        desc: "L'agent compare chaque semaine vos réalisations à votre budget par département et par poste. Il calcule les écarts, identifie les dérives et prépare un rapport avec les points d'attention. Vous intervenez sur les exceptions.",
        result: "Pilotage budgétaire hebdomadaire sans effort.",
      },
      { emoji: "19",
        title: "Préparation des clôtures mensuelles",
        desc: "L'agent prépare la checklist de clôture, relance automatiquement les responsables pour les pièces manquantes, vérifie la cohérence des données et vous signale les anomalies. La clôture avance même sans vous.",
        result: "Clôture accélérée de 2 jours. Moins de stress en fin de mois.",
      },
      { emoji: "20",
        title: "Consolidation multi-entités",
        desc: "Pour les groupes avec plusieurs entités, l'agent collecte les données de chaque filiale, les normalise selon votre plan de comptes groupe et génère la consolidation. Ce qui prenait 2 jours se fait en 2 heures.",
        result: "Consolidation groupe en 2h au lieu de 2 jours.",
      },
    ],
    faq: [
      { q: "Avec quels outils comptables l'agent est-il compatible ?", a: "Sage, Cegid, QuickBooks, Pennylane, FreshBooks, et tout outil qui exporte en CSV ou dispose d'une API. Claws évalue la compatibilité lors de l'appel découverte. Dans les cas extrêmes, l'agent peut travailler depuis des exports Excel." },
      { q: "Mes données financières sont-elles sécurisées ?", a: "C'est l'argument principal pour choisir une installation locale. Vos données financières restent sur votre machine, dans votre réseau. Aucun prestataire cloud ne peut y accéder. Conforme à la plupart des politiques de gouvernance des données." },
      { q: "L'agent peut-il faire de la prévision financière ?", a: "Il peut générer des projections basées sur vos données historiques et vos hypothèses. Ce ne sont pas des prévisions au sens actuariel, mais des outils d'aide à la décision rapides. Pour des modèles complexes, il prépare les données et les premiers drafts." },
      { q: "Est-ce adapté à une PME sans DAF dédié ?", a: "Oui. Beaucoup de PME ont un directeur général qui fait aussi office de DAF. Dans ce cas, l'agent devient d'autant plus précieux : il automatise la veille financière, le reporting et les alertes sans nécessiter d'expertise technique." },
    ],
    relatedPosts: [
      { slug: "openclaw-rgpd-donnees-locales", title: "OpenClaw et RGPD : vos données restent chez vous" },
      { slug: "agent-ia-veille-strategique-entreprise", title: "Agent IA pour la veille stratégique" },
    ],
  },

  retail: {
    slug: "retail",
    name: "Commerce & Retail",
    headline: "L'agent IA qui ne dort jamais pour que vous puissiez dormir.",
    subheadline: "Votre agent OpenClaw automatise le service client, les relances et la veille prix. Votre commerce tourne même quand vous êtes fermé.",
    metaTitle: "OpenClaw pour le commerce et le retail | Claws",
    metaDesc: "Claws installe OpenClaw pour le commerce et le retail. Service client 24/7, relances paniers, veille prix concurrents. Installation locale. À partir de 189€.",
    stat1: { value: "40%", label: "des questions clients = FAQ répétitives" },
    stat2: { value: "70%", label: "des paniers abandonnés jamais relancés" },
    stat3: { value: "2h", label: "pour être opérationnel" },
    painPoints: [
      { title: "Service client débordant", desc: "Heures d'ouverture, disponibilité produit, délais de livraison, retours. Les mêmes questions reviennent en boucle et prennent un temps disproportionné." },
      { title: "Paniers abandonnés perdus", desc: "70% des paniers abandonnés ne sont jamais relancés. Chaque relance non envoyée est du chiffre d'affaires laissé sur la table." },
      { title: "Veille prix impossible", desc: "Surveiller les prix de vos concurrents en ligne est un travail quotidien. Impossible à faire manuellement sur des centaines de références." },
      { title: "Gestion des avis clients", desc: "Répondre aux avis Google, aux messages Instagram, aux emails de réclamation, ça prend 1 à 2 heures par jour pour un commerce actif." },
    ],
    useCases: [
      { emoji: "21",
        title: "Service client 24/7",
        desc: "L'agent répond aux questions fréquentes (horaires, disponibilité, livraison, retours) sur WhatsApp, email ou Instagram DM, à toute heure. Les cas complexes sont transférés à un humain.",
        result: "40% des questions clients traitées sans intervention humaine.",
      },
      { emoji: "22",
        title: "Relances paniers abandonnés",
        desc: "L'agent surveille votre e-commerce et envoie une relance personnalisée 1h, 24h et 72h après un abandon de panier. Ton humain, message ciblé, pas un template générique.",
        result: "Récupération de 15 à 25% des paniers abandonnés.",
      },
      { emoji: "23",
        title: "Veille prix concurrents",
        desc: "L'agent surveille les prix de vos concurrents sur leurs sites et sur Amazon chaque jour. Il vous alerte quand un concurrent baisse ses prix significativement.",
        result: "Restez compétitif sans y passer votre dimanche.",
      },
      { emoji: "24",
        title: "Gestion des avis et réputation",
        desc: "L'agent surveille vos avis Google, Trustpilot et réseaux sociaux. Il prépare des réponses personnalisées (positives et négatives) que vous validez en un clic.",
        result: "Réponse à tous les avis, sans y passer 2h par jour.",
      },
      { emoji: "25",
        title: "Alertes rupture de stock",
        desc: "L'agent surveille vos niveaux de stock en temps réel et vous alerte avant la rupture. Il peut même déclencher automatiquement une commande fournisseur selon vos règles.",
        result: "Zéro rupture de stock non anticipée.",
      },
    ],
    faq: [
      { q: "L'agent peut-il s'intégrer à Shopify, WooCommerce, PrestaShop ?", a: "Oui. OpenClaw dispose de connecteurs pour les principales plateformes e-commerce. L'agent peut lire les commandes, les stocks et les clients directement depuis votre plateforme." },
      { q: "Le service client automatique ne va-t-il pas frustrer mes clients ?", a: "Bien configuré, non. L'agent répond aux questions simples en quelques secondes (mieux qu'un humain qui répond en 24h). Pour les questions complexes, il transfère à un humain clairement identifié. La plupart des clients préfèrent une réponse rapide à une attente longue." },
      { q: "Peut-on l'utiliser pour un commerce physique sans e-commerce ?", a: "Oui. L'agent peut gérer les messages Instagram, WhatsApp Business et les emails, même sans site de vente en ligne. Très utile pour les restaurateurs, fleuristes, coiffeurs, etc." },
      { q: "Comment l'agent connaît-il mes produits ?", a: "Vous lui fournissez votre catalogue (export CSV, Google Sheet ou lien vers votre site). Il apprend vos produits, vos prix et vos règles de retour lors de la configuration." },
    ],
    relatedPosts: [
      { slug: "agent-ia-service-client-pme", title: "Agent IA pour le service client PME" },
      { slug: "automatiser-relances-commerciales-agent-ia", title: "Automatiser les relances commerciales" },
    ],
  },
};

export const sectorSlugs = Object.keys(sectors);
